# Generated by Django 2.2 on 2021-05-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='description',
        ),
    ]
