# Generated by Django 2.2 on 2021-05-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_remove_description_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
        migrations.AddField(
            model_name='course',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
