# Generated by Django 2.2 on 2021-05-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='add description'),
            preserve_default=False,
        ),
    ]
